<a href="https://colab.research.google.com/github/tuongvi197ct22673/phantichdulieu/blob/main/lab02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Phần 1: Thống kê dữ liệu

1. Hãy sắp xếp dữ liệu điểm DH1 theo thứ tự tăng dần

In [ ]:
import pandas as pd
import sys
import seaborn as sns
import matplotlib.pyplot as plt

def load_data(filename):
  return pd.read_csv('https://raw.githubusercontent.com/tuongvi197ct22673/phantichdulieu-1/main/Data/'+filename)
dfcovid19 = load_data('dulieuxettuyendaihoc.csv')
dfcovid19.head()

   STT   T1   L1   H1   S1   V1   X1  ...  GT  DT   KV   DH1   DH2   DH3  KT
0    1  7.2  7.3  6.3  7.3  7.0  7.9  ...   F NaN  2NT  3.25  3.25  4.50  A1
1    2  5.4  3.9  3.9  4.0  5.4  5.4  ...   M NaN    1  6.00  4.00  3.50   C
2    3  5.6  6.8  7.2  7.5  4.3  7.4  ...   M NaN    1  5.00  6.75  4.00   C
3    4  6.6  6.4  5.3  6.9  5.4  7.3  ...   M NaN    1  4.25  4.25  5.25  D1
4    5  6.0  5.0  6.0  7.3  6.5  7.7  ...   M NaN  2NT  4.25  4.50  5.00   A

[5 rows x 56 columns]